### ISSUE TITLE
Las tareas deben de ir en la siguiente incidencia por ejemplo...aqui 

### ISSUE THREAD

**Issue by josealfredo79** [SistemasTecTlaxiaco/practicaprototipos-topicosavanzados-ide#2]
![image](https://user-images.githubusercontent.com/58342642/156098408-588719ee-6dc5-4a78-b913-8ad0f02b51b2.png)
Ejemplo de tarea en una incidencia 
https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-EDITH-R/issues/2

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/156098690-88cbf656-cea0-4531-9688-a681da117eb4.png)
Los pasos deben hacer una descripción de lo que se esta realizando
Favor de complementar la práctica

**Comment by Heidi-19** [comment]
Calificación de Practica 2: 19.4%

**Comment by Heidi-19** [comment]
Calificación Practica 2: 19.4%

**Comment by Heidi-19** [comment]
Calificación Practica 1: 18.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
